[package]
name = "open-graphene-fc"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/open-graphene/open-graphene"

[dependencies]
aes = "0.8"
bs58 = "0.5"
cbc = { version = "0.1", features = ["alloc"] }
getrandom = "0.2"
hex = "0.4"
hmac = "0.12"
ripemd = "0.1"
sha1 = "0.10"
secp256k1 = { version = "0.29", features = ["recovery"] }
sha2 = "0.10"
zeroize = { version = "1", features = ["derive"] }
