[package]
name = "open-graphene-core"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/open-graphene/open-graphene"

[dependencies]
open-graphene-primitives = { path = "../graphene-primitives" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
time = { version = "0.3", features = ["formatting", "parsing"] }
