use std::fs;
use std::path::{Path, PathBuf};

use open_graphene_json_schema::Protocol;

use crate::error::{GenBindingsRsError, Result};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GenerateBindingsResult {
    pub output_path: PathBuf,
    pub chain_id: String,
    pub schema_version: u32,
    pub rpc_method_count: usize,
    pub struct_count: usize,
    pub operation_count: usize,
}

pub fn generate_bindings(
    spec_path: impl AsRef<Path>,
    out_dir: impl AsRef<Path>,
) -> Result<GenerateBindingsResult> {
    let spec_path = spec_path.as_ref();
    let out_dir = out_dir.as_ref();

    let spec_json =
        fs::read_to_string(spec_path).map_err(|source| GenBindingsRsError::ReadSpec {
            path: spec_path.to_path_buf(),
            source,
        })?;
    let protocol: Protocol =
        serde_json::from_str(&spec_json).map_err(|source| GenBindingsRsError::ParseSpec {
            path: spec_path.to_path_buf(),
            source,
        })?;

    fs::create_dir_all(out_dir).map_err(|source| GenBindingsRsError::CreateOutDir {
        path: out_dir.to_path_buf(),
        source,
    })?;

    let output_path = out_dir.join("mod.rs");
    fs::write(&output_path, render_boilerplate(&protocol)).map_err(|source| {
        GenBindingsRsError::WriteOutput {
            path: output_path.clone(),
            source,
        }
    })?;

    Ok(GenerateBindingsResult {
        output_path,
        chain_id: protocol.chain.id,
        schema_version: protocol.schema_version,
        rpc_method_count: protocol.rpc_methods.len(),
        struct_count: protocol.structs.len(),
        operation_count: protocol.operations.len(),
    })
}

pub fn render_boilerplate(protocol: &Protocol) -> String {
    format!(
        "// Generated by open-graphene-gen-bindings-rs.\n\
         // Boilerplate output only: full Rust binding generation is not implemented yet.\n\n\
         pub const SCHEMA_VERSION: u32 = {schema_version};\n\
         pub const CHAIN_ID: &str = {chain_id};\n\
         pub const PUBLIC_KEY_PREFIX: &str = {public_key_prefix};\n\n\
         pub const STRUCT_COUNT: usize = {struct_count};\n\
         pub const ENUM_COUNT: usize = {enum_count};\n\
         pub const STATIC_VARIANT_COUNT: usize = {static_variant_count};\n\
         pub const OPERATION_COUNT: usize = {operation_count};\n\
         pub const OBJECT_TYPE_COUNT: usize = {object_type_count};\n\
         pub const RPC_API_COUNT: usize = {rpc_api_count};\n\
         pub const RPC_METHOD_COUNT: usize = {rpc_method_count};\n",
        schema_version = protocol.schema_version,
        chain_id = rust_string_literal(&protocol.chain.id),
        public_key_prefix = rust_string_literal(&protocol.chain.public_key_prefix),
        struct_count = protocol.structs.len(),
        enum_count = protocol.enums.len(),
        static_variant_count = protocol.static_variants.len(),
        operation_count = protocol.operations.len(),
        object_type_count = protocol.object_types.len(),
        rpc_api_count = protocol.rpc_apis.len(),
        rpc_method_count = protocol.rpc_methods.len(),
    )
}

fn rust_string_literal(value: &str) -> String {
    serde_json::to_string(value).expect("serializing a string literal cannot fail")
}

#[cfg(test)]
mod tests {
    use super::*;
    use open_graphene_json_schema::ChainDef;

    #[test]
    fn renders_basic_metadata_constants() {
        let output = render_boilerplate(&minimal_protocol());

        assert!(output.contains("Boilerplate output only"));
        assert!(output.contains("pub const CHAIN_ID: &str = \"swaplock\";"));
        assert!(output.contains("pub const PUBLIC_KEY_PREFIX: &str = \"BTS\";"));
        assert!(output.contains("pub const RPC_METHOD_COUNT: usize = 0;"));
    }

    fn minimal_protocol() -> Protocol {
        Protocol {
            schema_version: 1,
            chain: ChainDef {
                id: "swaplock".to_string(),
                public_key_prefix: "BTS".to_string(),
            },
            structs: vec![],
            enums: vec![],
            static_variants: vec![],
            operations: vec![],
            object_types: vec![],
            rpc_apis: vec![],
            rpc_methods: vec![],
            strict_mode: None,
        }
    }
}
