[chain]
id = "swaplock"
public_key_prefix = "BTS"
chain_id = "2267f694d96b7ffdcba1a98c63c09e720a18a85ad34954e299c66d5a42234098"

[source]
chain_repo = "../../../../blockchains/swaplock/swaplock-core"

[output]
dist = "./dist/swaplock.open-graphene.json"

[[rpc_apis]]
name = "database"
class = "database_api"
discover_method = "database"
methods = [
  "get_objects",
  "get_block_header",
  "get_block",
  "get_dynamic_global_properties",
  "get_limit_orders",
]

[[rpc_apis]]
name = "history"
class = "history_api"
discover_method = "history"
methods = [
  "get_account_history",
]
