[package]
name = "graphene"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "High-level Open Graphene Rust API facade."
repository = "https://github.com/open-graphene/open-graphene"

[dependencies]
graphene-chain-swaplock-api = { path = "../graphene-chain-swaplock/graphene-chain-swaplock-api" }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }

[[example]]
name = "swaplock_get_chain_id"
path = "examples/swaplock/get_chain_id.rs"

[[example]]
name = "swaplock_get_account"
path = "examples/swaplock/get_account.rs"

[[example]]
name = "swaplock_get_accounts"
path = "examples/swaplock/get_accounts.rs"

[[example]]
name = "swaplock_get_chain_properties"
path = "examples/swaplock/get_chain_properties.rs"

[[example]]
name = "swaplock_get_dynamic_global_properties"
path = "examples/swaplock/get_dynamic_global_properties.rs"

[[example]]
name = "swaplock_get_global_properties"
path = "examples/swaplock/get_global_properties.rs"

[[example]]
name = "swaplock_subscribe_dynamic_global_properties"
path = "examples/swaplock/subscribe_dynamic_global_properties.rs"
