// React-specific output consumes the shared IR; protocol types/codecs remain owned by bindings.
import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const check = process.argv.includes('--check');
const pascal = (value) =>
  value
    .split('_')
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join('');
for (const chain of ['swaplock', 'bitshares']) {
  const target = new URL(
    `../graphene-chain-${chain}/graphene-chain-${chain}-react/src/generated/`,
    import.meta.url,
  );
  await mkdir(target, { recursive: true });
  const raw = await readFile(
    new URL(
      `../../rust/graphene-chain-${chain}/graphene-chain-${chain}-spec/dist/${chain}.open-graphene.json`,
      import.meta.url,
    ),
    'utf8',
  );
  const spec = JSON.parse(raw);
  const queryMethods = spec.rpcMethods.filter(
    (m) =>
      ['database', 'history', 'orders'].includes(m.apiName) &&
      /^(get_|lookup_|list_)/.test(m.name) &&
      !m.isSubscription,
  );
  const mutations = spec.rpcMethods.filter((m) => !queryMethods.includes(m));
  const operations = spec.operations.filter((op) => !op.isVirtual);
  for (const m of mutations) {
    if (
      m.isSubscription ||
      !(
        m.apiName === 'crypto' ||
        (m.apiName === 'network_broadcast' &&
          m.name === 'broadcast_transaction')
      )
    ) {
      throw Error(
        'Missing React RPC lifecycle metadata: ' + m.apiName + '.' + m.name,
      );
    }
  }
  let output = `// Generated by scripts/generate-react.mjs. Do not edit.\n// Shared spec SHA-256: ${createHash('sha256').update(raw).digest('hex')}\nimport * as b from '@open-graphene/chain-${chain}-bindings';\nimport { SignedTransfer, type ${chain === 'bitshares' ? 'BitShares' : 'Swaplock'}Client, type TransactionOptions } from '@open-graphene/chain-${chain}-api';\nimport type { ReadOptions } from '@open-graphene/react-core';\nimport { adapter } from '../context.js';\n\n`;
  for (const m of queryMethods) {
    const symbol = pascal(m.apiName) + pascal(m.name);
    const options = symbol[0].toLowerCase() + symbol.slice(1) + 'Options';
    output += `export function ${options}(client: ${chain === 'bitshares' ? 'BitShares' : 'Swaplock'}Client, params: b.${symbol}Params, scope?: string) {\n  return adapter.rpcOptions(client, b.${symbol}, params, scope);\n}\n`;
    output += `export function use${symbol}<D = ReturnType<typeof b.${symbol}.parseReturns>>(params: b.${symbol}Params, options: ReadOptions<ReturnType<typeof b.${symbol}.parseReturns>, D> = {}) {\n  return adapter.useRpc(b.${symbol}, params, options);\n}\n`;
  }
  for (const m of mutations) {
    const symbol = pascal(m.apiName) + pascal(m.name);
    if (m.apiName === 'network_broadcast') {
      output += `/** Explicit submission; the SDK preserves ambiguous-broadcast handling. */\nexport function use${symbol}() {\n  return adapter.useAction(async (client, params: { readonly trx: b.SignedTransaction }) => {\n    await client.broadcast(new SignedTransfer(params.trx, 0));\n  });\n}\n`;
    } else {
      output += `/** Imperative RPC; never automatically retried or included in query keys. */\nexport function use${symbol}() {\n  return adapter.useAction((client, params: b.${symbol}Params) => client.rpc.invoke(b.${symbol}, params));\n}\n`;
    }
  }
  output += `const operationBuilders = b.bindOperationBuilders(operation => operation);\n`;
  for (const op of operations) {
    const factory = op.name.replace(/_operation$/, '');
    const symbol =
      factory === 'transfer' ? 'TransferOperation' : pascal(factory);
    const client = chain === 'bitshares' ? 'BitShares' : 'Swaplock';
    output += `export type Prepare${symbol}Input = Parameters<typeof operationBuilders.${factory}>[0];\n`;
    output += `export function prepare${symbol}(client: ${client}Client, input: Prepare${symbol}Input, options: TransactionOptions = {}) {\n  return client.prepareOperations([operationBuilders.${factory}(input)], options);\n}\n`;
    output += `/** Prepare and price only; signing and submission remain explicit. */\nexport function usePrepare${symbol}(options: TransactionOptions = {}) {\n  return adapter.useAction((client, input: Prepare${symbol}Input) => prepare${symbol}(client, input, options));\n}\n`;
  }
  output += `export const generatedRpcMutations = ${JSON.stringify(
    mutations.map((m) => m.apiName + '.' + m.name),
    null,
    2,
  )} as const;\n`;
  output += `export const generatedPrepareOperations = ${JSON.stringify(
    operations.map((op) => op.name.replace(/_operation$/, '')),
    null,
    2,
  )} as const;\n`;
  output += `export const generatedQueryMethods = ${JSON.stringify(
    queryMethods.map((m) => m.apiName + '.' + m.name),
    null,
    2,
  )} as const;\n`;
  const file = new URL('index.ts', target);
  if (check) {
    if ((await readFile(file, 'utf8')) !== output)
      throw Error('Generated React output drift: ' + chain);
  } else await writeFile(file, output);
  const extras = (await readdir(target)).filter((f) => f !== 'index.ts');
  if (extras.length)
    throw Error('Unmanaged generated React files: ' + extras.join(', '));
}
