// React-specific output consumes the shared IR; protocol types/codecs remain owned by bindings.
import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const check = process.argv.includes('--check');
const target = new URL('../graphene-react/src/generated/', import.meta.url);
await mkdir(target, { recursive: true });
const pascal = value => value.split('_').map(p => p[0].toUpperCase() + p.slice(1)).join('');
for (const chain of ['swaplock', 'bitshares']) {
  const raw = await readFile(new URL(`../../rust/graphene-chain-${chain}/graphene-chain-${chain}-spec/dist/${chain}.open-graphene.json`, import.meta.url), 'utf8');
  const spec = JSON.parse(raw);
  const queryMethods = spec.rpcMethods.filter(m => ['database', 'history', 'orders'].includes(m.apiName) && /^(get_|lookup_|list_)/.test(m.name) && !m.isSubscription);
  let output = `// Generated by scripts/generate-react.mjs. Do not edit.\n// Shared spec SHA-256: ${createHash('sha256').update(raw).digest('hex')}\nimport * as b from '@open-graphene/chain-${chain}-bindings';\nimport type { ${(chain === 'bitshares' ? 'BitShares' : 'Swaplock')}Client } from '@open-graphene/chain-${chain}-api';\nimport type { ReadOptions } from '../adapter.js';\nimport { adapter } from '../${chain}-context.js';\n\n`;
  for (const m of queryMethods) {
    const symbol = pascal(m.apiName) + pascal(m.name);
    const options = symbol[0].toLowerCase() + symbol.slice(1) + 'Options';
    output += `export function ${options}(client: ${(chain === 'bitshares' ? 'BitShares' : 'Swaplock')}Client, params: b.${symbol}Params, scope?: string) {\n  return adapter.rpcOptions(client, b.${symbol}, params, scope);\n}\n`;
    output += `export function use${symbol}<D = ReturnType<typeof b.${symbol}.parseReturns>>(params: b.${symbol}Params, options: ReadOptions<ReturnType<typeof b.${symbol}.parseReturns>, D> = {}) {\n  return adapter.useRpc(b.${symbol}, params, options);\n}\n`;
  }
  output += `export const generatedQueryMethods = ${JSON.stringify(queryMethods.map(m => m.apiName+'.'+m.name), null, 2)} as const;\n`;
  const file = new URL(chain+'.ts', target);
  if (check) { if (await readFile(file, 'utf8') !== output) throw Error('Generated React output drift: '+chain); }
  else await writeFile(file, output);
}
const extras = (await readdir(target)).filter(f => !['swaplock.ts','bitshares.ts'].includes(f));
if (extras.length) throw Error('Unmanaged generated React files: '+extras.join(', '));
