[package]
name = "open-graphene-sdk-operations"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/open-graphene/open-graphene"

[dependencies]
open-graphene-sdk-core = { path = "../graphene-sdk-core" }
open-graphene-sdk-primitives = { path = "../graphene-sdk-primitives" }
